#!/bin/bash - 
git apply /home/emomper/patch/libvirt-RHEL-screenshot-Implement-multiple-screen-support.patch
git apply /home/emomper/patch/libvirt-RHEL-Support-virtio-disk-hotplug-in-JSON-mode.patch
git apply /home/emomper/patch/libvirt-RHEL-Add-support-for-QMP-I-O-error-reason.patch
git apply /home/emomper/patch/libvirt-RHEL-qemu-support-relative-backing-for-RHEL-7.0.z-qemu.patch
git apply /home/emomper/patch/libvirt-RHEL-Fix-maxvcpus-output.patch
git apply /home/emomper/patch/libvirt-RHEL-Hack-around-changed-Broadwell-Haswell-CPUs.patch
git apply /home/emomper/patch/libvirt-RHEL-Add-rhel-machine-types-to-qemuDomainMachineNeedsFDC.patch
git apply /home/emomper/patch/libvirt-RHEL-qemu-Add-ability-to-set-sgio-values-for-hostdev.patch
git apply /home/emomper/patch/libvirt-RHEL-qemu-Add-check-for-unpriv-sgio-for-SCSI-generic-host-device.patch
git apply /home/emomper/patch/libvirt-RHEL-qemu-Support-vhost-user-multiqueue-with-QEMU-2.3.patch
git apply /home/emomper/patch/libvirt-RHEL-Define-ETHTOOL_-GS-COALESCE-when-building-on-older-kernels.patch
git apply /home/emomper/patch/libvirt-RHEL-cpu-Add-downstream-only-CPU-features-for-CVE-2017-5715.patch
git apply /home/emomper/patch/libvirt-qemu-Add-capability-for-the-HTM-pSeries-feature.patch
git apply /home/emomper/patch/libvirt-conf-Parse-and-format-the-HTM-pSeries-feature.patch
git apply /home/emomper/patch/libvirt-qemu-Format-the-HTM-pSeries-feature.patch
git apply /home/emomper/patch/libvirt-qemu-hotplug-Don-t-access-srcPriv-when-it-s-not-allocated.patch
git apply /home/emomper/patch/libvirt-qemuDomainNestedJobAllowed-Allow-QEMU_JOB_NONE.patch
git apply /home/emomper/patch/libvirt-src-Mention-DEVICE_REMOVAL_FAILED-event-in-virDomainDetachDeviceAlias-docs.patch
git apply /home/emomper/patch/libvirt-virsh.pod-Drop-persistent-for-detach-device-alias.patch
git apply /home/emomper/patch/libvirt-qemu-don-t-use-chardev-FD-passing-with-standalone-args.patch
git apply /home/emomper/patch/libvirt-qemu-remove-chardevStdioLogd-param-from-vhostuser-code-path.patch
git apply /home/emomper/patch/libvirt-qemu-consolidate-parameters-of-qemuBuildChrChardevStr-into-flags.patch
git apply /home/emomper/patch/libvirt-qemu-don-t-use-chardev-FD-passing-for-vhostuser-backend.patch
git apply /home/emomper/patch/libvirt-qemu-fix-UNIX-socket-chardevs-operating-in-client-mode.patch
git apply /home/emomper/patch/libvirt-qemuDomainDeviceDefValidateNetwork-Check-for-range-only-if-IP-prefix-set.patch
git apply /home/emomper/patch/libvirt-qemu-hotplug-Do-not-try-to-add-secret-object-for-TLS-if-it-does-not-exist.patch
git apply /home/emomper/patch/libvirt-qemu-monitor-Make-qemuMonitorAddObject-more-robust-against-programming-errors.patch
git apply /home/emomper/patch/libvirt-virDomainConfNWFilterInstantiate-initialize-xml-to-avoid-random-crash.patch
git apply /home/emomper/patch/libvirt-qemuProcessStartPRDaemonHook-Try-to-set-NS-iff-domain-was-started-with-one.patch
git apply /home/emomper/patch/libvirt-qemuDomainValidateStorageSource-Relax-PR-validation.patch
git apply /home/emomper/patch/libvirt-virStoragePRDefFormat-Suppress-path-formatting-for-migratable-XML.patch
git apply /home/emomper/patch/libvirt-qemu-Wire-up-PR_MANAGER_STATUS_CHANGED-event.patch
git apply /home/emomper/patch/libvirt-qemu_monitor-Introduce-qemuMonitorJSONGetPRManagerInfo.patch
git apply /home/emomper/patch/libvirt-qemu-Fetch-pr-helper-process-info-on-reconnect.patch
git apply /home/emomper/patch/libvirt-qemu-Fix-ATTRIBUTE_NONNULL-for-qemuMonitorAddObject.patch
git apply /home/emomper/patch/libvirt-virsh.pod-Fix-a-command-name-typo-in-nwfilter-binding-undefine.patch
git apply /home/emomper/patch/libvirt-docs-schema-Add-missing-alias-to-vsock-device.patch
git apply /home/emomper/patch/libvirt-virnetdevtap-Don-t-crash-on-ifname-in-virNetDevTapInterfaceStats.patch
git apply /home/emomper/patch/libvirt-qemu-hotplug-don-t-overwrite-error-message-in-qemuDomainAttachNetDevice.patch
git apply /home/emomper/patch/libvirt-qemu-hotplug-report-error-when-changing-rom-enabled-attr-for-net-iface.patch
git apply /home/emomper/patch/libvirt-qemu-Fix-setting-global_period-cputune-element.patch
git apply /home/emomper/patch/libvirt-tests-qemucaps-Add-test-data-for-upcoming-qemu-3.0.0.patch
git apply /home/emomper/patch/libvirt-qemu-capabilities-Add-capability-for-werror-rerror-for-usb-device-frontend.patch
git apply /home/emomper/patch/libvirt-qemu-command-Move-graphics-iteration-to-its-own-function.patch
git apply /home/emomper/patch/libvirt-qemu-address-Handle-all-the-video-devices-within-a-single-loop.patch
git apply /home/emomper/patch/libvirt-conf-Introduce-virDomainVideoDefClear-helper.patch
git apply /home/emomper/patch/libvirt-conf-Introduce-virDomainDefPostParseVideo-helper.patch
git apply /home/emomper/patch/libvirt-qemu-validate-Enforce-compile-time-switch-type-checking-for-videos.patch
git apply /home/emomper/patch/libvirt-tests-Add-capabilities-data-for-QEMU-2.11-x86_64.patch
git apply /home/emomper/patch/libvirt-tests-Update-capabilities-data-for-QEMU-3.0.0-x86_64.patch
git apply /home/emomper/patch/libvirt-qemu-qemuBuildHostdevCommandLine-Use-a-helper-variable-mdevsrc.patch
git apply /home/emomper/patch/libvirt-qemu-caps-Introduce-a-capability-for-egl-headless.patch
git apply /home/emomper/patch/libvirt-qemu-Introduce-a-new-graphics-display-type-headless.patch
git apply /home/emomper/patch/libvirt-qemu-caps-Add-vfio-pci.display-capability.patch
git apply /home/emomper/patch/libvirt-conf-Introduce-virDomainGraphicsDefHasOpenGL-helper.patch
git apply /home/emomper/patch/libvirt-conf-Replace-error-with-cleanup-in-virDomainHostdevDefParseXMLSubsys.patch
git apply /home/emomper/patch/libvirt-conf-Introduce-new-hostdev-attribute-display.patch
git apply /home/emomper/patch/libvirt-qemu-command-Enable-formatting-vfio-pci.display-option-onto-cmdline.patch
git apply /home/emomper/patch/libvirt-docs-Rephrase-the-mediated-devices-hostdev-section-a-bit.patch
git apply /home/emomper/patch/libvirt-conf-Introduce-new-video-type-none.patch
git apply /home/emomper/patch/libvirt-virt-xml-validate-Add-schema-for-nwfilterbinding.patch
git apply /home/emomper/patch/libvirt-tools-Fix-typo-generating-adapter_wwpn-field.patch
git apply /home/emomper/patch/libvirt-src-Fix-memory-leak-in-virNWFilterBindingDispose.patch
git apply /home/emomper/patch/libvirt-esx-storage-Fix-typo-lsilogic-lsiLogic.patch
git apply /home/emomper/patch/libvirt-networkGetDHCPLeases-Don-t-always-report-error-if-unable-to-read-leases-file.patch
git apply /home/emomper/patch/libvirt-nwfilter-Resolve-SEGV-for-NWFilter-Snoop-processing.patch
git apply /home/emomper/patch/libvirt-qemu-Remove-unused-bypassSecurityDriver-from-qemuOpenFileAs.patch
git apply /home/emomper/patch/libvirt-qemuDomainSaveMemory-Don-t-enforce-dynamicOwnership.patch
git apply /home/emomper/patch/libvirt-domain_nwfilter-Return-early-if-net-has-no-name-in-virDomainConfNWFilterTeardownImpl.patch
git apply /home/emomper/patch/libvirt-examples-Add-clean-traffic-gateway-into-nwfilters.patch
git apply /home/emomper/patch/libvirt-qemu-Exempt-video-model-none-from-getting-a-PCI-address-on-Q35.patch
git apply /home/emomper/patch/libvirt-conf-Fix-a-error-msg-typo-in-virDomainVideoDefValidate.patch
git apply /home/emomper/patch/libvirt-qemu_migration-Avoid-writing-to-freed-memory.patch
git apply /home/emomper/patch/libvirt-qemu-hotplug-Fix-asynchronous-unplug-of-shmem.patch
git apply /home/emomper/patch/libvirt-tests-rename-hugepages-to-hugepages-default.patch
git apply /home/emomper/patch/libvirt-tests-extract-hugepages-numa-default-dimm-out-of-hugepages-numa.patch
git apply /home/emomper/patch/libvirt-tests-rename-hugepages-numa-into-hugepages-numa-default.patch
git apply /home/emomper/patch/libvirt-tests-remove-unnecessary-XML-elements-from-hugepages-numa-default.patch
git apply /home/emomper/patch/libvirt-tests-extract-pages-discard-out-of-hugepages-pages.patch
git apply /home/emomper/patch/libvirt-tests-rename-hugepages-pages-into-hugepages-numa-nodeset.patch
git apply /home/emomper/patch/libvirt-tests-rename-hugepages-pages2-into-hugepages-numa-default-2M.patch
git apply /home/emomper/patch/libvirt-tests-extract-pages-discard-hugepages-out-of-hugepages-pages3.patch
git apply /home/emomper/patch/libvirt-tests-rename-hugepages-pages3-into-hugepages-numa-nodeset-part.patch
git apply /home/emomper/patch/libvirt-tests-rename-hugepages-pages4-into-hugepages-numa-nodeset-nonexist.patch
git apply /home/emomper/patch/libvirt-tests-rename-hugepages-pages5-into-hugepages-default-2M.patch
git apply /home/emomper/patch/libvirt-tests-rename-hugepages-pages6-into-hugepages-default-system-size.patch
git apply /home/emomper/patch/libvirt-tests-rename-hugepages-pages7-into-pages-dimm-discard.patch
git apply /home/emomper/patch/libvirt-tests-rename-hugepages-pages8-into-hugepages-nodeset-nonexist.patch
git apply /home/emomper/patch/libvirt-tests-introduce-hugepages-default-1G-nodeset-2M.patch
git apply /home/emomper/patch/libvirt-tests-introduce-hugepages-nodeset.patch
git apply /home/emomper/patch/libvirt-conf-Move-hugepage-XML-validation-check-out-of-qemu_command.patch
git apply /home/emomper/patch/libvirt-conf-Move-hugepages-validation-out-of-XML-parser.patch
git apply /home/emomper/patch/libvirt-conf-Introduce-virDomainDefPostParseMemtune.patch
git apply /home/emomper/patch/libvirt-tests-sev-Test-launch-security-with-specific-QEMU-version.patch
git apply /home/emomper/patch/libvirt-qemu-Fix-probing-of-AMD-SEV-support.patch
git apply /home/emomper/patch/libvirt-qemu-caps-Format-SEV-platform-data-into-qemuCaps-cache.patch
git apply /home/emomper/patch/libvirt-storage-Add-shrink-to-qemu-img-command-when-shrinking-vol.patch
git apply /home/emomper/patch/libvirt-access-Fix-nwfilter-binding-ACL-access-API-name-generation.patch
git apply /home/emomper/patch/libvirt-qemu-mdev-Use-vfio-pci-display-property-only-with-vfio-pci-mdevs.patch
git apply /home/emomper/patch/libvirt-virDomainDefCompatibleDevice-Relax-alias-change-check.patch
git apply /home/emomper/patch/libvirt-virDomainDetachDeviceFlags-Clarify-update-semantics.patch
git apply /home/emomper/patch/libvirt-virDomainNetDefCheckABIStability-Check-for-MTU-change-too.patch
git apply /home/emomper/patch/libvirt-conf-correct-false-boot-order-error-during-domain-parse.patch
git apply /home/emomper/patch/libvirt-security-dac-also-label-listen-UNIX-sockets.patch
git apply /home/emomper/patch/libvirt-qemu-fix-up-permissions-for-pre-created-UNIX-sockets.patch
git apply /home/emomper/patch/libvirt-virFileIsSharedFSType-Check-for-fuse.glusterfs-too.patch
git apply /home/emomper/patch/libvirt-virfile-fix-cast-align-error.patch
git apply /home/emomper/patch/libvirt-virfiletest-Fix-test-name-prefix-for-virFileInData-test.patch
git apply /home/emomper/patch/libvirt-virfiletst-Test-virFileIsSharedFS.patch
git apply /home/emomper/patch/libvirt-virFileIsSharedFSType-Detect-direct-mount-points.patch
git apply /home/emomper/patch/libvirt-virfile-Rework-virFileIsSharedFixFUSE.patch
git apply /home/emomper/patch/libvirt-virfile-Take-symlink-into-account-in-virFileIsSharedFixFUSE.patch
git apply /home/emomper/patch/libvirt-qemu-Properly-report-VIR_DOMAIN_EVENT_RESUMED_FROM_SNAPSHOT.patch
git apply /home/emomper/patch/libvirt-qemu-Report-more-appropriate-running-reasons.patch
git apply /home/emomper/patch/libvirt-qemu-Pass-running-reason-to-RESUME-event-handler.patch
git apply /home/emomper/patch/libvirt-qemu-Map-running-reason-to-resume-event-detail.patch
git apply /home/emomper/patch/libvirt-qemu-Avoid-duplicate-resume-events-and-state-changes.patch
git apply /home/emomper/patch/libvirt-qemu-Don-t-ignore-resume-events.patch
git apply /home/emomper/patch/libvirt-qemu-Fix-post-copy-migration-on-the-source.patch
git apply /home/emomper/patch/libvirt-RHEL-cpu_map-Mark-arch-facilities-feature-as-non-migratable.patch
git apply /home/emomper/patch/libvirt-virfile-Detect-ceph-as-shared-FS.patch
git apply /home/emomper/patch/libvirt-util-Don-t-overflow-in-virRandomBits.patch
git apply /home/emomper/patch/libvirt-virrandom-Avoid-undefined-behaviour-in-virRandomBits.patch
git apply /home/emomper/patch/libvirt-cputest-Add-data-for-Intel-R-Xeon-R-CPU-E5-2630-v4.patch
git apply /home/emomper/patch/libvirt-cputest-Add-data-for-Intel-R-Core-TM-i7-7600U.patch
git apply /home/emomper/patch/libvirt-cputest-Add-data-for-Intel-R-Xeon-R-CPU-E7540.patch
git apply /home/emomper/patch/libvirt-cputest-Add-data-for-Intel-R-Xeon-R-CPU-E5-2650.patch
git apply /home/emomper/patch/libvirt-cputest-Add-data-for-Intel-R-Core-TM-i7-8700.patch
git apply /home/emomper/patch/libvirt-cpu_x86-Separate-signature-parsing-from-x86ModelParse.patch
git apply /home/emomper/patch/libvirt-cpu_x86-Add-x86ModelCopySignatures-helper.patch
git apply /home/emomper/patch/libvirt-cpu_x86-Store-CPU-signature-in-an-array.patch
git apply /home/emomper/patch/libvirt-cpu_x86-Allow-multiple-signatures-for-a-CPU-model.patch
git apply /home/emomper/patch/libvirt-cpu_map-Add-hex-representation-of-signatures.patch
git apply /home/emomper/patch/libvirt-cpu_map-Add-more-signatures-for-Conroe-CPU-model.patch
git apply /home/emomper/patch/libvirt-cpu_map-Add-more-signatures-for-Penryn-CPU-model.patch
git apply /home/emomper/patch/libvirt-cpu_map-Add-more-signatures-for-Nehalem-CPU-models.patch
git apply /home/emomper/patch/libvirt-cpu_map-Add-more-signatures-for-Westmere-CPU-model.patch
git apply /home/emomper/patch/libvirt-cpu_map-Add-more-signatures-for-SandyBridge-CPU-models.patch
git apply /home/emomper/patch/libvirt-cpu_map-Add-more-signatures-for-IvyBridge-CPU-models.patch
git apply /home/emomper/patch/libvirt-cpu_map-Add-more-signatures-for-Haswell-CPU-models.patch
git apply /home/emomper/patch/libvirt-cpu_map-Add-more-signatures-for-Broadwell-CPU-models.patch
git apply /home/emomper/patch/libvirt-cpu_map-Add-more-signatures-for-Skylake-Client-CPU-models.patch
git apply /home/emomper/patch/libvirt-cpu-Don-t-access-invalid-memory-in-virCPUx86Translate.patch
git apply /home/emomper/patch/libvirt-cpu_x86-Log-decoded-CPU-model-and-signatures.patch
git apply /home/emomper/patch/libvirt-util-Modify-virStorageFileGetSCSIKey-return.patch
git apply /home/emomper/patch/libvirt-storage-Rework-virStorageBackendSCSISerial.patch
git apply /home/emomper/patch/libvirt-util-Introduce-virStorageFileGetNPIVKey.patch
git apply /home/emomper/patch/libvirt-storage-Fetch-a-unique-key-for-vHBA-NPIV-LUNs.patch
git apply /home/emomper/patch/libvirt-RHEL-qemu-Alter-val-usage-in-qemuSetUnprivSGIO.patch
git apply /home/emomper/patch/libvirt-RHEL-qemu-Alter-qemuSetUnprivSGIO-hostdev-shareable-logic.patch
git apply /home/emomper/patch/libvirt-qemu-Filter-non-SCSI-hostdevs-in-qemuHostdevPrepareSCSIDevices.patch
git apply /home/emomper/patch/libvirt-qemu-Fix-logic-error-in-qemuSetUnprivSGIO.patch
git apply /home/emomper/patch/libvirt-qemu-Fix-crash-trying-to-use-iSCSI-hostdev.patch
git apply /home/emomper/patch/libvirt-src-Document-autostart-for-session-demon.patch
git apply /home/emomper/patch/libvirt-nwfilter-Add-extra-verbiage-for-binding-create-delete.patch
git apply /home/emomper/patch/libvirt-qemu-Remove-duplicated-qemuAgentCheckError.patch
git apply /home/emomper/patch/libvirt-qemu-require-reply-from-guest-agent-in-qemuAgentGetInterfaces.patch
git apply /home/emomper/patch/libvirt-virsh-Add-missed-fields-to-pool-define-as-item-entry.patch
git apply /home/emomper/patch/libvirt-qemu-Add-entry-for-balloon-stat-stat-disk-caches.patch
git apply /home/emomper/patch/libvirt-qemu-Set-identity-for-the-reconnect-all-thread.patch
git apply /home/emomper/patch/libvirt-docs-schemas-Fix-missing-timestamp-inside-backingStore.patch
git apply /home/emomper/patch/libvirt-storage-Remove-secretPath-from-_virStorageBackendQemuImgInfo.patch
git apply /home/emomper/patch/libvirt-storage-Allow-for-inputvol-to-have-any-format-for-encryption.patch
git apply /home/emomper/patch/libvirt-storage-Allow-inputvol-to-be-encrypted.patch
git apply /home/emomper/patch/libvirt-virsh-man-Document-quirks-of-device-detach-and-friends.patch
git apply /home/emomper/patch/libvirt-virsh-man-Document-asynchronous-behaviour-of-detach-device-alias.patch
git apply /home/emomper/patch/libvirt-access-Modify-the-VIR_ERR_ACCESS_DENIED-to-include-driverName.patch
git apply /home/emomper/patch/libvirt-qemu-Put-format-raw-onto-cmd-line-for-SCSI-passthrough.patch
git apply /home/emomper/patch/libvirt-virnwfilterbindingobj-Introduce-and-use-virNWFilterBindingObjStealDef.patch
git apply /home/emomper/patch/libvirt-logging-ensure-pending-I-O-is-drained-before-reading-position.patch
git apply /home/emomper/patch/libvirt-conf-Fix-check-for-chardev-source-path.patch
git apply /home/emomper/patch/libvirt-util-skip-RDMA-detection-for-non-PCI-network-devices.patch
git apply /home/emomper/patch/libvirt-qemu-Set-job-statsType-for-external-memory-snapshot.patch
git apply /home/emomper/patch/libvirt-virsh-Strip-XML-declaration-when-extracting-CPU-XMLs.patch
git apply /home/emomper/patch/libvirt-virsh-Require-explicit-domain-for-domxml-to-native.patch
git apply /home/emomper/patch/libvirt-storage-Extract-out-mount-command-creation-for-FS-Backend.patch
git apply /home/emomper/patch/libvirt-storage-Move-FS-backend-mount-creation-command-helper.patch
git apply /home/emomper/patch/libvirt-storage-Move-virStorageBackendFileSystemGetPoolSource.patch
git apply /home/emomper/patch/libvirt-tests-Introduce-tests-for-storage-pool-xml-to-argv-checks.patch
git apply /home/emomper/patch/libvirt-tests-Add-storagepool-xml-test-for-netfs-auto.patch
git apply /home/emomper/patch/libvirt-storage-Rework-virStorageBackendFileSystemMountCmd.patch
git apply /home/emomper/patch/libvirt-storage-Add-default-mount-options-for-fs-netfs-storage-pools.patch
git apply /home/emomper/patch/libvirt-conf-Add-optional-NFS-Source-Pool-protocol-ver-n-option.patch
git apply /home/emomper/patch/libvirt-storage-Add-the-nfsvers-to-the-command-line.patch
git apply /home/emomper/patch/libvirt-virsh-Add-source-protocol-ver-for-pool-commands.patch
git apply /home/emomper/patch/libvirt-RHEL-conf-storage-Fix-a-memory-leak-in-virStoragePoolDefParseSource.patch
git apply /home/emomper/patch/libvirt-tests-Reuse-qemucapabilities-data-for-qemucaps2xml.patch
git apply /home/emomper/patch/libvirt-tests-Add-more-tests-to-qemucaps2xml.patch
git apply /home/emomper/patch/libvirt-qemu-Drop-QEMU_CAPS_ENABLE_KVM.patch
git apply /home/emomper/patch/libvirt-qemu-Avoid-probing-non-native-binaries-all-the-time.patch
git apply /home/emomper/patch/libvirt-qemu-Clarify-QEMU_CAPS_KVM.patch
git apply /home/emomper/patch/libvirt-qemu-Don-t-check-for-dev-kvm-presence.patch
git apply /home/emomper/patch/libvirt-tests-Follow-up-on-qemucaps2xmldata-rename.patch
git apply /home/emomper/patch/libvirt-qemu-hotplug-Don-t-generate-alias-when-detaching-disk.patch
git apply /home/emomper/patch/libvirt-qemu-hotplug-Don-t-generate-alias-when-detaching-controllers.patch
git apply /home/emomper/patch/libvirt-tests-add-channel-unix-guestfwd.patch
git apply /home/emomper/patch/libvirt-qemu-Use-tmpChr-in-qemuDomainDetachChrDevice-to-build-device-string.patch
git apply /home/emomper/patch/libvirt-qemuL-Drop-user-prefix-for-guestfwd-netdev.patch
git apply /home/emomper/patch/libvirt-qemu_hotplug-Attach-guestfwd-using-netdev_add.patch
git apply /home/emomper/patch/libvirt-qemu_hotplug-Detach-guestfwd-using-netdev_del.patch
git apply /home/emomper/patch/libvirt-qemuhotplugtest-Test-guestfwd-attach-and-detach.patch
git apply /home/emomper/patch/libvirt-qemu_hotplug-Don-t-build-device-string-in-qemuDomainDetachChrDevice.patch
git apply /home/emomper/patch/libvirt-qemu_hotplug-Assume-chardev-alias-always-exists-in-qemuDomainDetachChrDevice.patch
git apply /home/emomper/patch/libvirt-qemu-fix-device-name-passed-to-error-report.patch
git apply /home/emomper/patch/libvirt-qemu_hotplug-Properly-check-for-qemuMonitorDelDevice-retval.patch
git apply /home/emomper/patch/libvirt-qemu_hotplug-Introduce-and-use-qemuDomainDeleteDevice.patch
git apply /home/emomper/patch/libvirt-qemu-hotplug-Remove-ret-variable-in-qemuDomainDetachDeviceDiskLive.patch
git apply /home/emomper/patch/libvirt-qemu-hotplug-Use-typecasted-enum-in-qemuDomainDetachDeviceDiskLive.patch
git apply /home/emomper/patch/libvirt-qemu-hotplug-Use-switch-statement-for-selecting-disk-bus-function.patch
git apply /home/emomper/patch/libvirt-qemu-hotplug-Merge-virtio-and-non-virtio-disk-unplug-code.patch
git apply /home/emomper/patch/libvirt-qemu_hotplug-remove-unnecessary-check-for-valid-PCI-address.patch
git apply /home/emomper/patch/libvirt-qemu_hotplug-rename-a-virDomainDeviceInfoPtr-to-avoid-confusion.patch
git apply /home/emomper/patch/libvirt-qemu_hotplug-eliminate-multiple-identical-qemuDomainDetachHost-Device-functions.patch
git apply /home/emomper/patch/libvirt-qemu_hotplug-eliminate-unnecessary-call-to-qemuDomainDetachNetDevice.patch
git apply /home/emomper/patch/libvirt-qemu_hotplug-refactor-qemuDomainDetachDiskLive-and-qemuDomainDetachDiskDevice.patch
git apply /home/emomper/patch/libvirt-qemu_hotplug-don-t-call-DetachThisHostDevice-for-hostdev-network-devices.patch
git apply /home/emomper/patch/libvirt-qemu_hotplug-merge-qemuDomainDetachThisHostDevice-into-qemuDomainDetachHostDevice.patch
git apply /home/emomper/patch/libvirt-qemu_hotplug-move-qemuDomainChangeGraphicsPasswords.patch
git apply /home/emomper/patch/libvirt-qemu_hotplug-move-almost-all-qemuDomainDetach-functions-together.patch
git apply /home/emomper/patch/libvirt-qemu_hotplug-move-Attach-Detach-Lease-functions-with-others-of-same-type.patch
git apply /home/emomper/patch/libvirt-qemu_hotplug-move-qemuDomainDetachDeviceLive-to-qemu_hotplug.c.patch
git apply /home/emomper/patch/libvirt-qemu_hotplug-remove-extra-function-in-middle-of-DetachController-call-chain.patch
git apply /home/emomper/patch/libvirt-qemu_hotplug-pull-qemuDomainUpdateDeviceList-out-of-qemuDomainDetachDeviceLive.patch
git apply /home/emomper/patch/libvirt-test-replace-calls-to-individual-detach-functions-with-one-call-to-main-detach.patch
git apply /home/emomper/patch/libvirt-qemu_hotplug-make-Detach-functions-called-only-from-qemu_hotplug.c-static.patch
git apply /home/emomper/patch/libvirt-qemu_hotplug-rename-dev-to-match-in-qemuDomainDetachDeviceLive.patch
git apply /home/emomper/patch/libvirt-qemu_hotplug-separate-Chr-Lease-from-other-devices-in-DetachDevice-switch.patch
git apply /home/emomper/patch/libvirt-qemu_hotplug-standardize-the-names-args-calling-of-qemuDomainDetach.patch
git apply /home/emomper/patch/libvirt-qemu_hotplug-rename-Chr-and-Lease-Detach-functions.patch
git apply /home/emomper/patch/libvirt-qemu_hotplug-new-function-qemuDomainRemoveAuditDevice.patch
git apply /home/emomper/patch/libvirt-qemu_hotplug-audit-all-auditable-device-types-in-qemuDomainRemoveAuditDevice.patch
git apply /home/emomper/patch/libvirt-qemu_hotplug-consolidate-all-common-detach-code-in-qemuDomainDetachDeviceLive.patch
git apply /home/emomper/patch/libvirt-qemu_hotplug-don-t-shutdown-net-device-until-the-guest-has-released-it.patch
git apply /home/emomper/patch/libvirt-qemu_hotplug-delay-sending-DEVICE_REMOVED-event-until-after-all-teardown.patch
git apply /home/emomper/patch/libvirt-conf-Expose-virDomainSCSIDriveAddressIsUsed.patch
git apply /home/emomper/patch/libvirt-qemuhotplugtest-Don-t-plug-a-SCSI-disk-at-unit-7.patch
git apply /home/emomper/patch/libvirt-qemu_hotplug-Check-for-duplicate-drive-addresses.patch
git apply /home/emomper/patch/libvirt-qemu-Rework-setting-process-affinity.patch
git apply /home/emomper/patch/libvirt-qemu-Set-up-EMULATOR-thread-and-cpuset.mems-before-exec-ing-qemu.patch
git apply /home/emomper/patch/libvirt-cpu_map-Add-features-for-Icelake-CPUs.patch
git apply /home/emomper/patch/libvirt-cpu_map-Add-Icelake-CPU-models.patch
git apply /home/emomper/patch/libvirt-cpu_x86-Do-not-cache-microcode-version.patch
git apply /home/emomper/patch/libvirt-qemu-Don-t-cache-microcode-version.patch
git apply /home/emomper/patch/libvirt-util-Rename-some-functions-of-virresctrl.patch
git apply /home/emomper/patch/libvirt-util-Refactor-virResctrlGetInfo-in-virresctrl.patch
git apply /home/emomper/patch/libvirt-util-Refactor-virResctrlAllocFormat-of-virresctrl.patch
git apply /home/emomper/patch/libvirt-util-Add-MBA-capability-information-query-to-resctrl.patch
git apply /home/emomper/patch/libvirt-util-Add-MBA-check-to-virResctrlInfoGetCache.patch
git apply /home/emomper/patch/libvirt-util-Add-MBA-allocation-to-virresctrl.patch
git apply /home/emomper/patch/libvirt-util-Add-MBA-schemata-parse-and-format-methods.patch
git apply /home/emomper/patch/libvirt-util-Add-support-to-calculate-MBA-utilization.patch
git apply /home/emomper/patch/libvirt-util-Introduce-virResctrlAllocForeachMemory.patch
git apply /home/emomper/patch/libvirt-util-Introduce-virResctrlAllocSetMemoryBandwidth.patch
git apply /home/emomper/patch/libvirt-conf-Rename-cachetune-to-resctrl.patch
git apply /home/emomper/patch/libvirt-conf-Factor-out-vcpus-parsing-part-from-virDomainCachetuneDefParse.patch
git apply /home/emomper/patch/libvirt-conf-Factor-out-vcpus-overlapping-from-virDomainCachetuneDefParse.patch
git apply /home/emomper/patch/libvirt-conf-Factor-out-virDomainResctrlDef-update-from-virDomainCachetuneDefParse.patch
git apply /home/emomper/patch/libvirt-conf-Add-support-for-memorytune-XML-processing-for-resctrl-MBA.patch
git apply /home/emomper/patch/libvirt-conf-Add-return-value-check-to-virResctrlAllocForeachCache.patch
git apply /home/emomper/patch/libvirt-conf-Add-memory-bandwidth-allocation-capability-of-host.patch
git apply /home/emomper/patch/libvirt-conf-Fix-bug-in-finding-alloc-through-matching-vcpus.patch
git apply /home/emomper/patch/libvirt-resctrl-Do-not-calculate-free-bandwidth-for-MBA.patch
git apply /home/emomper/patch/libvirt-resctrl-Set-MBA-defaults-properly.patch
git apply /home/emomper/patch/libvirt-resctrl-Fix-testing-line.patch
git apply /home/emomper/patch/libvirt-virresctrl-fix-MBA-memory-leak.patch
git apply /home/emomper/patch/libvirt-test-caps-Add-capabilities-for-QEMU-3.1.0.patch
git apply /home/emomper/patch/libvirt-util-Introduce-virHostGetDRMRenderNode-helper.patch
git apply /home/emomper/patch/libvirt-conf-Introduce-virDomainGraphics-related-helpers.patch
git apply /home/emomper/patch/libvirt-qemu-process-spice-Pick-the-first-available-DRM-render-node.patch
git apply /home/emomper/patch/libvirt-qemu-command-Introduce-qemuBuildGraphicsEGLHeadlessCommandLine-helper.patch
git apply /home/emomper/patch/libvirt-qemu-caps-Introduce-QEMU_EGL_HEADLESS_RENDERNODE-capability.patch
git apply /home/emomper/patch/libvirt-conf-gfx-Add-egl-headless-as-a-member-to-virDomainGraphicsDef-struct.patch
git apply /home/emomper/patch/libvirt-conf-gfx-egl-headless-Introduce-a-new-gl-subelement.patch
git apply /home/emomper/patch/libvirt-qemu-domain-egl-headless-Add-the-DRI-device-into-the-namespace.patch
git apply /home/emomper/patch/libvirt-qemu-cgroup-gfx-egl-headless-Add-the-DRI-device-into-the-cgroup-list.patch
git apply /home/emomper/patch/libvirt-security-dac-gfx-egl-headless-Relabel-the-DRI-device.patch
git apply /home/emomper/patch/libvirt-qemu-command-gfx-egl-headless-Add-rendernode-option-to-the-cmdline.patch
git apply /home/emomper/patch/libvirt-domain-conf-graphics-Fix-picking-DRI-renderer-automatically-for-SPICE.patch
git apply /home/emomper/patch/libvirt-qemu-domain-gfx-Fix-shadowing-of-a-function-argument-in-validation.patch
git apply /home/emomper/patch/libvirt-qemu_hotplug-Initialize-charAlias-in-qemuDomainRemoveChrDevice.patch
git apply /home/emomper/patch/libvirt-Handle-copying-bitmaps-to-larger-data-buffers.patch
git apply /home/emomper/patch/libvirt-nwfilter-fix-adding-std-MAC-and-IP-values-to-filter-binding.patch
git apply /home/emomper/patch/libvirt-util-suppress-unimportant-ovs-vsctl-errors-when-getting-interface-stats.patch
git apply /home/emomper/patch/libvirt-cpu_map-Add-support-for-cldemote-CPU-feature.patch
git apply /home/emomper/patch/libvirt-cputest-Add-data-for-Intel-R-Xeon-R-CPU-E3-1225-v5.patch
git apply /home/emomper/patch/libvirt-cpu_map-Define-md-clear-CPUID-bit.patch
git apply /home/emomper/patch/libvirt-admin-reject-clients-unless-their-UID-matches-the-current-UID.patch
git apply /home/emomper/patch/libvirt-locking-restrict-sockets-to-mode-0600.patch
git apply /home/emomper/patch/libvirt-logging-restrict-sockets-to-mode-0600.patch
git apply /home/emomper/patch/libvirt-util-require-command-args-to-be-non-NULL.patch
git apply /home/emomper/patch/libvirt-qemu-use-line-breaks-in-command-line-args-written-to-log.patch
git apply /home/emomper/patch/libvirt-virfile-added-GPFS-as-shared-fs.patch
git apply /home/emomper/patch/libvirt-util-file-introduce-VIR_AUTOCLOSE-macro-to-close-fd-of-the-file-automatically.patch
git apply /home/emomper/patch/libvirt-vircpuhost-Add-support-for-reading-MSRs.patch
git apply /home/emomper/patch/libvirt-virhostcpu-Make-virHostCPUGetMSR-work-only-on-x86.patch
git apply /home/emomper/patch/libvirt-qemu-Make-virQEMUCapsProbeHostCPUForEmulator-more-generic.patch
git apply /home/emomper/patch/libvirt-qemuargv2xmltest-Use-mocked-virQEMUCapsProbeHostCPU.patch
git apply /home/emomper/patch/libvirt-util-Add-virHostCPUGetTscInfo.patch
git apply /home/emomper/patch/libvirt-conf-Report-TSC-frequency-in-host-CPU-capabilities.patch
git apply /home/emomper/patch/libvirt-cpu_x86-Fix-placement-of-CheckFeature-functions.patch
git apply /home/emomper/patch/libvirt-cpu_x86-Probe-TSC-frequency-and-scaling-support.patch
git apply /home/emomper/patch/libvirt-qemu-Check-TSC-frequency-before-starting-QEMU.patch
git apply /home/emomper/patch/libvirt-util-Propagate-numad-failures-correctly.patch
git apply /home/emomper/patch/libvirt-util-alloc-add-macros-for-implementing-automatic-cleanup-functionality.patch
git apply /home/emomper/patch/libvirt-util-bitmap-define-cleanup-function-using-VIR_DEFINE_AUTOPTR_FUNC.patch
git apply /home/emomper/patch/libvirt-util-Introduce-virBitmapUnion.patch
git apply /home/emomper/patch/libvirt-util-Introduce-virNumaNodesetToCPUset.patch
git apply /home/emomper/patch/libvirt-qemu-Fix-qemuProcessInitCpuAffinity.patch
git apply /home/emomper/patch/libvirt-qemu-Fix-leak-in-qemuProcessInitCpuAffinity.patch
git apply /home/emomper/patch/libvirt-cpu_conf-Fix-XPath-for-parsing-TSC-frequency.patch
git apply /home/emomper/patch/libvirt-qemu-Drop-cleanup-label-from-qemuProcessInitCpuAffinity.patch
git apply /home/emomper/patch/libvirt-qemu-Fix-NULL-pointer-access-in-qemuProcessInitCpuAffinity.patch
git apply /home/emomper/patch/libvirt-api-disallow-virDomainSaveImageGetXMLDesc-on-read-only-connections.patch
git apply /home/emomper/patch/libvirt-api-disallow-virDomainManagedSaveDefineXML-on-read-only-connections.patch
git apply /home/emomper/patch/libvirt-api-disallow-virConnectGetDomainCapabilities-on-read-only-connections.patch
git apply /home/emomper/patch/libvirt-api-disallow-virConnect-HypervisorCPU-on-read-only-connections.patch
git apply /home/emomper/patch/libvirt-qemu-Pass-qemuCaps-to-qemuDomainDefCopy.patch
git apply /home/emomper/patch/libvirt-qemu-Pass-qemuCaps-to-qemuDomainDefFormatBufInternal.patch
git apply /home/emomper/patch/libvirt-qemu-Pass-qemuCaps-to-qemuDomainSaveImageOpen.patch
git apply /home/emomper/patch/libvirt-qemu-Pass-qemuCaps-to-qemuMigrationAnyPrepareDef.patch
git apply /home/emomper/patch/libvirt-qemu-Pass-correct-qemuCaps-to-virDomainDefParseString.patch
git apply /home/emomper/patch/libvirt-qemu-Pass-qemuCaps-to-qemuMigrationCookieXMLParse.patch
git apply /home/emomper/patch/libvirt-qemu-Pass-correct-qemuCaps-to-virDomainDefCopy.patch
git apply /home/emomper/patch/libvirt-qemu-Pass-correct-qemuCaps-to-virDomainDefPostParse.patch
git apply /home/emomper/patch/libvirt-qemu-Pass-correct-qemuCaps-to-virDomainDefParseNode.patch
git apply /home/emomper/patch/libvirt-qemu-Pass-correct-qemuCaps-to-virDomainDeviceDefPostParse.patch
git apply /home/emomper/patch/libvirt-qemu-Fix-crash-on-incoming-migration.patch
